// Scenario model. EVERY input is an ASSUMPTION (see docs/research for the price evidence). Not a forecast.
// Usage: node scripts/financial-model.mjs [hardwareCostUSD] > docs/FINANCIAL_MODEL.md
const hardware = Number(process.argv[2] ?? 0) || null;
const scenarios = {
  CONSERVATIVE: { price: 399, setup: 297, cogs: 75, churn: 0.08, cac: 900, fixed: 600, note: 'Discounted pricing, high churn, expensive acquisition' },
  BASE:         { price: 599, setup: 497, cogs: 60, churn: 0.05, cac: 500, fixed: 500, note: 'Growth-tier price hypothesis from research' },
  AGGRESSIVE:   { price: 799, setup: 497, cogs: 55, churn: 0.03, cac: 250, fixed: 500, note: 'Premium price holds, referrals lower CAC' },
};
const sizes = [1, 5, 10, 25, 50, 100, 250, 500];
const $ = n => `$${Math.round(n).toLocaleString('en-US')}`;
const out = [];
out.push('# Financial model (scenarios, not forecasts)\n');
out.push('Generated by `scripts/financial-model.mjs`. Every number is an **ASSUMPTION** until real customers replace it.');
out.push('COGS = Twilio/SMS + A2P fees + number + LLM + payment fees + support time per customer per month. Fixed = hosting, DB, tools, domain per month, plus an assumed $4k/mo support hire per 40 customers beyond 25.');
out.push('CAC = all sales cost per closed customer (founder time valued at 0 in early customers - **this flatters CAC**).');
out.push('LTV = gross profit per month / monthly churn. Payback = CAC / gross profit per month.\n');
for (const [name, s] of Object.entries(scenarios)) {
  const gp = s.price - s.cogs, gm = gp / s.price, ltv = gp / s.churn;
  out.push(`## ${name}\n_${s.note}._ Price ${$(s.price)}/mo + ${$(s.setup)} setup, COGS ${$(s.cogs)}/mo, churn ${s.churn * 100}%/mo, CAC ${$(s.cac)}, fixed ${$(s.fixed)}/mo.\n`);
  out.push(`Gross margin **${(gm * 100).toFixed(0)}%** | LTV **${$(ltv)}** | LTV:CAC **${(ltv / s.cac).toFixed(1)}** | CAC payback **${(s.cac / gp).toFixed(1)} months**\n`);
  out.push('| Customers | MRR | ARR | COGS/mo | Gross profit/mo | Opex/mo | Net/mo (before CAC) | Break-even? |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (const n of sizes) {
    const opex = s.fixed + (n > 25 ? Math.ceil((n - 25) / 40) * 4000 : 0); // +1 support/CS hire ($4k/mo, assumption) per 40 customers beyond 25
    const mrr = n * s.price, cogs = n * s.cogs, g = mrr - cogs, net = g - opex;
    out.push(`| ${n} | ${$(mrr)} | ${$(mrr * 12)} | ${$(cogs)} | ${$(g)} | ${$(opex)} | ${$(net)} | ${net >= 0 ? 'yes' : 'no'} |`);
  }
  const be = Math.ceil(s.fixed / gp);
  out.push(`\nOperating break-even at **${be} customers** (excluding founder pay and CAC).`);
  if (hardware) {
    const first = s.price + s.setup;
    const months = Math.ceil((hardware / (gp - 0)) );
    out.push(`Hardware payback (${$(hardware)} outlay): needs ~${Math.ceil(hardware / gp)} customer-months of gross profit; with 1 new customer per month it is roughly month ${Math.ceil(Math.sqrt(2 * hardware / gp))}. First-month cash per customer incl. setup: ${$(first)}.`);
  } else out.push('Hardware payback: pass the machine cost as an argument (`node scripts/financial-model.mjs 3000`) to compute it.');
  out.push('');
}
out.push('## What would invalidate this\n- Churn: home-service SMBs churn fast if they cannot see recovered jobs; the dashboard exists to fight this.\n- COGS at scale depends on A2P 10DLC fees and carrier pass-through, verify with current Twilio pricing.\n- CAC is guessed. The first 20 outreach conversations will replace it with a measured number.');
console.log(out.join('\n'));
